@echo off
echo Starting Contractor Safety Field Audits Dashboard...
echo Checking dependencies...
python -m pip install -r requirements.txt
echo Launching Streamlit...
python -m streamlit run app.py
pause
